"""empty message

Revision ID: 6137d590964f
Revises: bc6cfc0565a3
Create Date: 2023-08-24 19:51:14.968918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6137d590964f'
down_revision = 'bc6cfc0565a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('form', sa.String(length=20), nullable=False),
    sa.Column('active', sa.String(length=60), nullable=False),
    sa.Column('entry_time', sa.String(length=20), nullable=False),
    sa.Column('exit_time', sa.String(length=20), nullable=True),
    sa.Column('total_hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
