"""empty message

Revision ID: c4b8cec1b0a1
Revises: 6137d590964f
Create Date: 2023-08-27 23:10:37.845506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b8cec1b0a1'
down_revision = '6137d590964f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hours', sa.Integer(), nullable=True))
        batch_op.drop_column('total_hour')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_hour', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_hours')

    # ### end Alembic commands ###
