"""empty message

Revision ID: fb7e25676b9d
Revises: c4b8cec1b0a1
Create Date: 2023-09-13 18:10:46.738209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7e25676b9d'
down_revision = 'c4b8cec1b0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('pubisher', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['author'])
        batch_op.create_unique_constraint(None, ['pubisher'])

    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('pubisher', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['author'])
        batch_op.create_unique_constraint(None, ['pubisher'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pubisher')
        batch_op.drop_column('author')

    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pubisher')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
